# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-05 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='forum_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default=' ', max_length=1024)),
                ('question', models.TextField(default=' ', max_length=1024)),
                ('answers', models.TextField(default=' ', max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='info',
            field=models.TextField(blank=True, default=' ', max_length=10024),
        ),
    ]
