# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-07 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
